kind: pipeline
name: default
type: docker

steps:
- name: kaniko  
  image: plugins/kaniko
  settings:
    repo: registry.andrey.wtf/hass-supervised-docker
    username: "qweritos"
    password: "123qweasd"