kind: pipeline
name: default
type: docker

steps:
- name: kaniko  
  image: plugins/kaniko
  settings:
    repo: registry.andrey.wtf/hass-supervised-docker
    username: "qweritos"
    password: "dckr_pat_fZiAd7gaW7FnsCFK6MmRttxwyfw"
    enable-cache: true